# Generated by Django 5.1.2 on 2024-10-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verbtherapy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_text", models.TextField()),
                ("blank1_text", models.CharField(blank=True, max_length=100)),
                ("blank2_text", models.CharField(blank=True, max_length=100)),
                ("blank3_text", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
